# Generated by Django 2.2 on 2019-05-14 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Question Category',
                'verbose_name_plural': 'Question Categories',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskType', models.CharField(max_length=30)),
                ('has_additional_description', models.BooleanField()),
                ('description', models.TextField()),
                ('additional_description', models.TextField(blank=True)),
                ('answer', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='CompletedQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionresults', models.CharField(max_length=20)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.QuestionCategory', verbose_name='related category')),
            ],
            options={
                'verbose_name': 'Completed Questions',
                'verbose_name_plural': 'Completed Questions',
            },
        ),
    ]
